# Generated by Django 3.2.18 on 2023-03-09 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessNotationCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.TextField(unique=True)),
                ('checkpoint', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChessOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
                ('uci', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessPuzzleThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
                ('moves', models.TextField()),
                ('url', models.URLField()),
                ('opening_fam', models.TextField()),
                ('opening_variation', models.TextField()),
                ('theme', models.ManyToManyField(to='api.ChessPuzzleThemes')),
            ],
        ),
        migrations.CreateModel(
            name='ChessNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.TextField()),
                ('black', models.TextField()),
                ('white_elo', models.IntegerField()),
                ('black_elo', models.IntegerField()),
                ('site', models.TextField()),
                ('mainline', models.TextField()),
                ('opening', models.TextField()),
                ('opening_fam', models.TextField()),
                ('eco', models.CharField(max_length=10)),
                ('event', models.TextField()),
                ('result', models.TextField()),
                ('avg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notation', to='api.chesselo')),
            ],
        ),
    ]
