# Generated by Django 3.2.16 on 2023-01-31 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessELO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessMainline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessNotationCheckPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, unique=True)),
                ('checkpoint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ChessPuzzles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='NotationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vers', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChessNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.CharField(max_length=100)),
                ('black', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('mainline', models.TextField()),
                ('opening', models.TextField()),
                ('event', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=20)),
                ('avg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notation', to='api.chesselo')),
            ],
        ),
        migrations.CreateModel(
            name='ChessFenNextMoves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('black', models.IntegerField()),
                ('next_move', models.CharField(max_length=10)),
                ('fen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_move', to='api.chessprocess')),
            ],
        ),
    ]
