# Generated by Django 3.2.18 on 2023-03-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chesspuzzle',
            name='theme',
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='theme',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='ChessPuzzleThemes',
        ),
    ]
