# Generated by Django 3.2.16 on 2023-02-01 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessfennextmoves',
            name='cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessprocess',
            name='fen',
            field=models.TextField(unique=True),
        ),
    ]
