# Generated by Django 3.2.16 on 2023-02-01 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230201_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessfennextmoves',
            name='fen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_moves', to='api.chessprocess'),
        ),
    ]
