# Generated by Django 3.2.18 on 2023-03-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230313_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='chesspuzzle',
            name='one_time_solved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
