# Generated by Django 3.2.16 on 2023-02-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_chessfennextmoves_fen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chessnotation',
            name='black',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chessnotation',
            name='event',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chessnotation',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chessnotation',
            name='site',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chessnotation',
            name='white',
            field=models.TextField(),
        ),
    ]
