# Generated by Django 3.2.17 on 2023-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230201_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessnotationcheckpoint',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chessfennextmoves',
            name='black',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessfennextmoves',
            name='draw',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessfennextmoves',
            name='white',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chessnotationcheckpoint',
            name='fname',
            field=models.TextField(unique=True),
        ),
    ]
