# Generated by Django 3.2.18 on 2023-02-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230202_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.TextField()),
                ('uci', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
