# Generated by Django 3.2.18 on 2023-02-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_chessopening'),
    ]

    operations = [
        migrations.AddField(
            model_name='chessopening',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
