# Generated by Django 3.2.18 on 2023-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230222_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChessPuzzleThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(unique=True)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='chesspuzzle',
            name='theme',
        ),
        migrations.AddField(
            model_name='chesspuzzle',
            name='theme',
            field=models.ManyToManyField(to='api.ChessPuzzleThemes'),
        ),
    ]
