# Generated by Django 3.2.18 on 2023-02-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20230223_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalseMigaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
