# Generated by Django 3.2.18 on 2023-02-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_falsemigaration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FalseMigaration',
        ),
    ]
